### ISSUE TITLE
Thoughts on aborting wren fibers / vms

### ISSUE THREAD

**Issue by etherealbacon** [stevewoolcock/WrenSharp#3]
I am using WrenSharp for executing client side made scripts on the server side which is a fairly hot potato to be juggling.

In an effort to prevent end users from writing while(true) loops and bricking up the server side i was looking for a way to abort VMS from C# which from experimenting so far is not possible without generating memory violations / exceptions.

I even attempted to run Fiber.abort inside the VM but i still cannot persuade it to abort the running vm / code.

I saw that someone else had a similar problem in at 
https://github.com/wren-lang/wren/commit/78112912d5936018a54ab0fd65c0e8119e89f1ee#diff-0dc729e8863a7755a45fb887260378dcec6b924471c18eaa3b88f6e86fc606d3R125-R129

Where they have hacked in the funcitonality into the base wren lib the ability to end a vm / main fiber after the current iteration.

If i was to implement this, is it something that would be welcome as a PR to WrenSharp? It may require a custom fork of the base Wren lib.

Also it appears that the base wren libs are pre-built and included as dll / libs for each platform. Could you confirm i have missed a rogue C source code somewhere?

**Comment by stevewoolcock** [comment]
If your Wren VM is running on a main thread, how would `earlyExit` be set? An infinite loop would be blocking the calling thread. Are you imagining there's a background thread watching the VM to trigger it after a timeout?

If you Wren VM is already running on another thread, could you not just abort the thread after a timeout? Or are we looking for a graceful way to terminate the VM without aborting threads?

**Comment by stevewoolcock** [comment]
Yes, fair. Aborting threads is also a deprecated API that throws `PlatformNotSupportedException` in most dotnet environments as it has potential to corrupt the program state.

Microsoft's official guidance on this is to use cancellation tokens, however that's not possible where 3rd party code is running that does not support cancellation tokens - which is the case for you, running user code you have no control over - so the suggested alternative is to run it in a separate process and kill the process instead: https://learn.microsoft.com/en-us/dotnet/standard/threading/destroying-threads

That obviously complicates things if you're expecting a return result from the scripts, or allowing the scripts to modify program your program's state. But it's a potential solution.

While I'm not totally adverse to the idea of modifying the Wren source to support something like this (the WrenSharp Unity IL2CPP library has modified Wren source), but it would need to be clearly separated from the main WrenSharp code base as it's an extension and not available by default. How exactly to go about that I'd need to consider.

The API for providing the functionality is also a consideration. Assuming you call `WrenVM.Interpret(...)` on some user code that causes an infinite loop, it will be blocking the calling thread indefinitely. The fibre's exit flag will need to be set from another thread. What does the API look like for forcefully terminating the fibre from the monitoring thread? How would you retrieve a pointer to the target Fibre from the VM instance to be able to set the flag?

**Comment by stevewoolcock** [comment]
This sounds like a decent solution using the tools available without any modifications.

Enforcing rules and validating your user's scripts is a good approach. I think Wren's syntax is simple enough that it should be doable. Forcing yields within loops allows you also to control the compute time allocated to them.
