### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by mduszenko** [stevewoolcock/WrenSharp#6]
Hello! I cannot seem to find any nuget packages for this library. I tested some basic scenarios by referencing the source code directly and everything worked well. Are there any plans for publishing a package? Is the project considered mature enough to use?

**Comment by stevewoolcock** [comment]
Apologies for the delayed reply.

> **Are there any plans for publishing a package?**
There is no Nuget package for the project at the moment, and I don't have any plans to create one currently. The main reasons being:
- There are two targets in the repo currently, one for plain C# and one for the Unity game engine. These would need to be separated.
- A modified version of the Wren native library is currently part of the library (WrenSharp.Lib.NetStandard and WrenSharp.Lib.Unity) that contains some extensions I've added to make working with the libraries easier. The native library extensions can be excluded by removing the WRENSHARP_EXT conditional.

The project would need several Nuget packages to cover the possible use cases for all users, which increases the maintenance overheads for the project.

As it stands currently, users should include the parts of the project they need directly, compile it and include the binaries as they see fit, or possibly use git submodules if appropraite.

> **Is the project considered mature enough to use?**
I am currently using this library in a private cross-platform project. Although not yet in production, but has been tested on multiple platforms without issues. It should be very stable, however I would urge you to test integrations on your target platforms.
